# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fergus Findley - blog
email: fergusfindley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Fergus Findley - a data science and Machine Learning enthusiast. I like to practice and do some projects about data science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fergusfindley.github.io" # the base hostname & protocol for your site
usernames:
  twitter: 
  github:  fergusfindley
  linkedin: 
  stackexchange: 
  delicious: 
  pinboard: 

# Build settings
markdown: kramdown
timezone: "+0100"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
      mathjax:  false
      social:   true
